### ISSUE TITLE
Uninstalling flex

### ISSUE THREAD

**Issue by hardik-vala** [druths/xp#11]
How do I perform a safe uninstall of flex? Do I just have to remove the symlink `/usr/local/bin/fx`?

**Comment by druths** [comment]
How did you install it?  If through pip, then you can just use “pip install”.  If through setup.py, then you might just go ahead and delete the flex package from site-packages, the symlink /usr/local/bin/fx and the fx script that the /usr/local/bin/fx points to.

**Comment by hardik-vala** [comment]
I was an early adopter and used the setup.py. Thanks.
