### ISSUE TITLE
$PLN($MY_CONST) error

### ISSUE THREAD

**Issue by hardik-vala** [druths/xp#13]
Referencing a declared constant inside the `$PLN()` directive, like so,

```
MY_CONST=some_value

my_task:
	code.sh:
		echo $PLN($MY_CONST)
```

results in the following error:

```
ERROR: parsing error on line 7: expected to find a ")", none found
```

Is this a genuine bug or a pattern users should avoid?

**Comment by druths** [comment]
I think this pattern should be supported.  Will check into it tomorrow.
