### ISSUE TITLE
Using a variable from another pipeline

### ISSUE THREAD

**Issue by hardik-vala** [druths/xp#15]
Is it possible to use a variable from another pipeline? For example,

```
# Pipeline: my_pipeline

use my_other_pipeline as mop

my_task:
    code.sh:
        echo $mop.VAR # This currently is not supported.
```

**Comment by druths** [comment]
No, currently no support for that.  What’s an example of where you’d want to do that?

**Comment by hardik-vala** [comment]
Use case: I find defining a path to a resource multiple times results in brittle code, so I collect all paths to shared resources (e.g. CoreNLP models) into a single "resource manager" that I use in my working modules. Hence, in xp, I'd like to define a "resource manager" pipeline that I can connect to my other pipelines that do work. Or is there a better way of implementing this pattern in xp?

Anyways, that particular use case aside, it feels incomplete to be able to refer to tasks in another pipeline but not variables.

**Comment by druths** [comment]
I agree on both points.  And the idea of a resource manager is a cool idea, more generally ... I wonder if that should be formalized in some way - I wonder if there's something here we should formalize (i.e., dependence on resource manager variables is special).  Thoughts?

**Comment by hardik-vala** [comment]
One thing that makes using xp enjoyable is its simplicity so I'm hesitant to introduce new constructs, especially those that favour certain design patterns over others. But do you have anything specific in mind?

**Comment by druths** [comment]
Nothing in mind - you're the power user :) I totally agree. And using a combination of variables and tasks, you could build pretty much any kind of dependency structure.

**Comment by druths** [comment]
Done!  To reference a variable in another pipeline, you need to surround the reference with curly braces:

  echo ${earlier_pln.great_var}
